[package]
name = "encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.9"
dirs = "6.0.0"

chacha20poly1305 = "0.10"
scrypt = "0.11" # Or latest compatible version
rand = "0.9.1"